Add summarisation part of the NorGLM NO-Multi-QA-Sum dataset
ScandEval/ScandEval pull request #580
Opened 2024-11-01 12:56 UTC by viggo-gascou

Added the [NorGLM NO-Multi-QA-Sum dataset](https://huggingface.co/datasets/NorGLM/NO-Multi-QA-Sum)

I have tried to use the dataset by running
scandeval --model mhenrichsen/danskgpt-tiny --dataset norglm-multi-sum. I do not seem to get any errors, although it is running rather slow (I think this is a standing issue with my machine - have not tried to debug further yet).

Fixes part of #536

The dataset is somewhat small and consists of 467 samples with the following splits:

- 147 training samples
- 64 validation samples
- 256 test samples

Working on adding the question and answer part of the same dataset as well.

2024-11-01 14:01 UTC, viggo-gascou commented
From inspection of the question and answer part of the dataset it seems that not many of the answers can directly be found in the article or the summary (only 15). So it probably does not make sense to include the question and answer part of the dataset unless we do some reformulation of all the answers to ensure the answer can be found in the context. How do you think I should proceed @saattrupdan?

2024-11-04 09:47 UTC, viggo-gascou commented
Hmm it looks like there are a few duplicate articles as well but with different summaries and questions see them [here](https://huggingface.co/datasets/NorGLM/NO-Multi-QA-Sum/embed/sql-console/default/train?sql_console=true&views%5B%5D=train&sql=--+The+SQL+console+is+powered+by+DuckDB+WASM+and+runs+entirely+in+the+browser.%0A--+Get+started+by+typing+a+query+or+selecting+a+view+from+the+options+below.%0ASELECT+*+FROM+train+WHERE+article+IN+%28+SELECT+article+FROM+train+GROUP+BY+article+HAVING+COUNT%28*%29+%3E+1+%29+ORDER+BY+article+). Additionally, I found an "article" which was just a bunch of questions and answers from a quiz of some sort see [here](https://huggingface.co/datasets/NorGLM/NO-Multi-QA-Sum/embed/sql-console/default/train?sql_console=true&views%5B%5D=train&sql=--+The+SQL+console+is+powered+by+DuckDB+WASM+and+runs+entirely+in+the+browser.%0A--+Get+started+by+typing+a+query+or+selecting+a+view+from+the+options+below.%0ASELECT+*+FROM+train+WHERE+%22Unnamed%3A+0%22+%3D+%27359%27&sql_row=0). If I remove the duplicate articles and the non-article entry the total number of samples drops to 451 (that is keeping one of the duplicate articles). We could remove all duplicates or just choose a random one, not sure which is better?

2024-11-07 10:27 UTC, saattrupdan commented
> From inspection of the question and answer part of the dataset it seems that not many of the answers can directly be found in the article or the summary (only 15). So it probably does not make sense to include the question and answer part of the dataset unless we do some reformulation of all the answers to ensure the answer can be found in the context. How do you think I should proceed @saattrupdan?

This is similar to the Icelandic QA dataset that @oliverkinch looked at ([link](https://github.com/ScandEval/ScandEval/pull/564)) - you can try to mimic his approach with reformulating the answers. But it should probably be in a separate PR, as this one focuses on the summarisation part.

2024-11-07 10:28 UTC, saattrupdan commented
> Hmm it looks like there are a few duplicate articles as well but with different summaries and questions see them [here](https://huggingface.co/datasets/NorGLM/NO-Multi-QA-Sum/embed/sql-console/default/train?sql_console=true&views%5B%5D=train&sql=--+The+SQL+console+is+powered+by+DuckDB+WASM+and+runs+entirely+in+the+browser.%0A--+Get+started+by+typing+a+query+or+selecting+a+view+from+the+options+below.%0ASELECT+*+FROM+train+WHERE+article+IN+%28+SELECT+article+FROM+train+GROUP+BY+article+HAVING+COUNT%28*%29+%3E+1+%29+ORDER+BY+article+). Additionally, I found an "article" which was just a bunch of questions and answers from a quiz of some sort see [here](https://huggingface.co/datasets/NorGLM/NO-Multi-QA-Sum/embed/sql-console/default/train?sql_console=true&views%5B%5D=train&sql=--+The+SQL+console+is+powered+by+DuckDB+WASM+and+runs+entirely+in+the+browser.%0A--+Get+started+by+typing+a+query+or+selecting+a+view+from+the+options+below.%0ASELECT+*+FROM+train+WHERE+%22Unnamed%3A+0%22+%3D+%27359%27&sql_row=0). If I remove the duplicate articles and the non-article entry the total number of samples drops to 451 (that is keeping one of the duplicate articles). We could remove all duplicates or just choose a random one, not sure which is better?

I think we just choose a random one of them (with a random seed, of course). With 451 samples we could have a test set of 256, use 64 for validation and the remaining 131 for training, say.

2024-11-07 10:31 UTC, saattrupdan requested changes
Looks good! Just a couple of smaller things.

2024-11-07 10:31 UTC, saattrupdan commented on CHANGELOG.md
> +  Norwegian benchmarks. It has been marked as `unofficial` for now.
Typo:

```suggestion
  dataset NO-Multi-QA-Sum (`norglm-multi-sum`). This dataset is part of the NLEBench
  Norwegian benchmarks. It has been marked as `unofficial` for now.
```

2024-11-07 10:31 UTC, saattrupdan commented on src/scripts/create_norglm_multisum.py
> +
```suggestion
```

2024-11-07 10:31 UTC, saattrupdan commented on src/scripts/create_norglm_multisum.py
> +    train_df = filtered_df.sample(n=train_size, random_state=4242)
No need to specify the train size, as it is simply the rest:

```suggestion
    train_df = filtered_df[~filtered_df.index.isin(test_df.index)]
```

2024-11-08 08:34 UTC, viggo-gascou commented
fixed now, commit didn't update for some reason 😅

2024-11-12 07:59 UTC, saattrupdan approved these changes
LGTM!

2024-11-14 08:49 UTC, merged